config/routes.rb
Lifelinei::Application.routes.draw do

  # Root path:
  root                                      to: 'home#index'
  match '/login',                           to: 'portals#login'
  match '/aed',                             to: 'portals#aed'
  match '/ampride',                         to: 'portals#ampride'
  match '/customerlead',                    to: 'portals#customerlead'
  match '/ems',                             to: 'portals#ems'
  match '/jli',                             to: 'portals#jli'
  match '/landolakes',                      to: 'portals#landolakes'
  match '/lifeline',                        to: 'portals#lifeline'
  match '/maximum',                         to: 'portals#maximum'
  match '/mayo',                            to: 'portals#mayo'
  match '/portalfull',                      to: 'portals#portalfull'
  match '/w9',                              to: 'portals#w9'
  match '/optin',                           to: 'portals#optin'
  match '/laws',                            to: 'portals#laws'
  match '/trainerupdate',                   to: 'portals#trainer_update'
  match '/accounting',                      to: 'portals#accounting'
  match '/shipping',                        to: 'portals#shipping'
  match '/training',                        to: 'portals#training'
  match '/budget',                          to: 'portals#budget'
  match '/compliance',                      to: 'portals#compliance'
  match '/pasttraining',                    to: 'portals#past_training'
  match '/futuretraining',                  to: 'portals#future_training'
  match '/useragreement',                   to: 'portals#useragreement'
  match '/privacy',                         to: 'portals#privacy'


  match 'survey' => 'surveys#new',          to: 'new_survey_path'

  # About Us paths;
  get "about_us/main",                      as:  'about_us'
  get "about_us/mission",                   as:  'mission'
  get "about_us/partners",                  as:  'partners'
  get "about_us/help",                      as:  'help'

  # Solutions_path:
  # get "solutions/main",                     as: "solutions"
  # get "solutions/schools",                  as: "schools"
  # get "solutions/police",                   as: "police"
  # get "solutions/businesses",               as: "businesses"
  # get "solutions/fire",                     as: "fire"
  # get "solutions/dentists",                 as: "dentists"
  # get "solutions/churches",                 as: "churches"
  # get "solutions/individuals",              as: "individuals"

  # Products paths:
  get "products/main",                      as: 'products'
  get "products/aeds",                      as: 'aeds'
  get "products/accessories",               as: 'accessories'
  get "products/comparison",                as: 'comparison'
  get "products/registration",              as: 'registration'

  # Training paths:
  get "training/main",                      as: 'training'
  get "training/certified",                 as: 'certified'

  # Support & Services paths:
  get "services/main",                      as:   'services'
  get "services/administration",            as:   'administration'
  get "services/oversight",                 as:   'oversight'
  get "services/monitor",                   as:   'monitor'

  # Customer Portal paths:
  get 'portals/lifeline',                   as: 'lifeline'
  get 'portals/jli',                        as: 'jli'
  get 'portals/mayo',                       as: 'mayo'
  get 'portals/ems',                        as: 'ems'
  get 'portals/landolakes',                 as: 'landolakes'
  get 'portals/ampride',                    as: 'ampride'
  get 'portals/customerlead',               as: 'customerlead'
  get 'portals/portalfull',                 as: 'portalfull'
  get 'portals/aed',                        as: 'aed'
  get 'portals/maximum',                    as: 'maximum'
  get 'portals/login',                      as: 'portal_login'
  get 'portals/useragreement',              as: 'useragreement'
  get 'portals/privacy',                    as: 'privacy'

  # Customer Login paths:
  get 'customers/login',                    as: 'login'

  # RESTful routes:
  resources                                 :contacts
  resources                                 :surveys, except: [ :index, :show ]
  resources                                 :users

end

app/views/layouts/_footer.erb
<div class="one_third"><!-- FIRST COLUMN -->
  <h3>Latest Tweets</h3><!-- BLOG UPDATES -->
  <div class="footer_post">
    <a class="twitter-timeline" width="305" height="350" href="https://twitter.com/LifeLine" data-widget-id="261568544356044800">Tweets by @LifeLine</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div><!-- END TWITTER UPDDATES -->
</div><!-- END FIRST COLUMN -->
<div class="one_third"><!-- SECOND COLUMN -->
  <h3>Useful Links</h3>
  <ul class="blogroll">
    <li><%= link_to 'FDA Safety', "http://www.fda.gov/Safety/MedWatch/default.htm", :target => "_blank" %></li>
    <li><%= link_to 'American Heart Association', "http://www.heart.org", :target => "_blank" %></li>
    <li><%= link_to 'European Resuscitation Council', "https://www.erc.edu", :target => "_blank" %></li>
    <li><%= link_to 'ILCOR', "http://www.ilcor.org", :target => "_blank" %></li>
  </ul>
</div><!-- END SECOND COLUMN -->
<div class="one_third_last"><!-- THIRD COLUMN -->
  <h3>Follow Us</h3>
  <ul class="social_icons">
    <li><%= link_to 'Contact Us', new_contact_path, :class => 'email' %></li>
    <li><%= link_to 'Facebook', "http://www.facebook.com/LifeLinei", :class => 'facebook', :target => "_blank"  %></li>
    <li><%= link_to 'Twitter', "http://www.twitter.com/lifeline", :class => 'twitter', :target => "_blank"  %></li>
    <li><%= link_to 'LinkedIn', "http://www.linkedin.com/company/lifeline-incorporated", :class => 'linkedin', :target => "_blank"  %></li>
    <li><%= link_to 'YouTube', "http://www.youtube.com/user/LifeLineSupport?feature=mhee", :class => 'youtube', :target => "_blank"  %></li>
    <li><%= link_to 'Pinterest', "http://www.pinterest.com/lifelinei/", :class => 'pinterest', :target => "_blank"  %></li>
  </ul>
</div><!-- END THIRD COLUMN -->

app/views/layouts/_footer_bottom.erb
<div id="footer_bottom"><!-- FOOTER BOTTOM -->
  <div class="info">
    <div id="foot_left"><!-- FOOT LEFT -->
      <p>Copyright&copy; 2012 LifeLine Incorporated.  All rights reserved.</p>
    </div><!-- END FOOT LEFT -->
    <div id="foot_right"><!-- FOOT RIGHT -->
      <div class="top-footer"><%= link_to 'Top', "#", :class => "link-top" %></div>
      <ul>
        <li><%= link_to 'Privacy', privacy_path %></li>
        <li><%= link_to 'Terms', useragreement_path %></li>
        <li><%= link_to 'Home', root_path %></li>
        <li>Phone:  612-729-1888</li>
        <li><%= link_to 'Contact Us', new_contact_path %></li>
      </ul>
    </div><!-- END FOOT RIGHT -->
  </div><!-- END INFO -->
</div><!-- END FOOTER BOTTOM -->

app/views/layouts/_head_tag.erb
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<%= favicon_link_tag %>
<title><%= full_title(yield(:title)) %></title>
<%= stylesheet_link_tag 'style', 'karma-grey', 'secondary-grey' %>
<%= javascript_include_tag 'jquery-1.5.min', 'karma', 'application' %>
<!--[if lte IE 8]><%= stylesheet_link_tag 'lt8' %>><![endif]-->
<!--[if IE 8]><%= stylesheet_link_tag 'ie8' %>><![endif]-->
<%= csrf_meta_tag %>

app/views/layouts/_header_area.erb
<!-- LOGO -->
<%= link_to image_tag('logo400x200.png', :size => '200x100'), root_path, :class => 'logo' %>
<!-- END LOGO -->

<!-- MAIN NAVIGATION -->
<ul id="menu-main-nav">
  <li class=<%= get_controller_klass('about_us') %>><!-- ABOUT US MENU -->
    <%= link_to about_us_path do %>
        <span><strong>About Us</strong><span class="navi-description">about our company</span></span>
    <% end %>
    <ul class="sub-menu">
      <li><%= link_to new_contact_path do %><span>Contact Us</span><% end %></li>
      <li><%= link_to mission_path do %><span>Our Mission</span><% end %></li>
      <li><%= link_to partners_path do %><span>Our Partners</span><% end %></li>
      <li><%= link_to help_path do %><span>Help</span><% end %></li>
      <li><%= link_to "#" do %><span>Customer Login</span><% end %></li>
      <li><%= link_to about_us_path do %><span>About Us</span><% end %></li>
    </ul>
  </li><!-- END ABOUT US LIVE MENU -->
  <li class=<%= get_controller_klass('products') %>><!-- PRODUCTS MENU -->
    <%= link_to products_path do %>
        <span><strong>Product Solutions</strong><span class="navi-description">about our products</span></span>
    <% end %>
    <ul class="sub-menu">
      <li><%= link_to aeds_path do %><span>Automated External Defibrillators</span><% end %></li>
      <li><%= link_to accessories_path do %><span>AED Accessories</span><% end %></li>
      <li><%= link_to comparison_path do %><span>AED Comparison</span><% end %></li>
      <li><%= link_to registration_path do %><span>AED Registration</span><% end %></li>
      <li><%= link_to products_path do %><span>Product Solutions</span><% end %></li>
    </ul>
  </li><!-- END PRODUCTS MENU -->
  <li class=<%= get_controller_klass('training') %>><!-- TRAINING MENU -->
    <%= link_to training_path do %>
        <span><strong>Training Solutions</strong><span class="navi-description">about our training</span></span>
    <% end %>
    <ul class="sub-menu">
      <li><%= link_to certified_path do %><span>Certified Training</span><% end %></li>
      <li><%= link_to new_survey_path do %><span>Class Survey</span><% end %></li>
      <li><%= link_to training_path do %><span>Training Solutions</span><% end %></li>
    </ul>
  </li><!-- END TRAINING MENU -->
  <li class=<%= get_controller_klass('services') %>><!-- SERVICES MENU -->
    <%= link_to services_path do %>
        <span><strong>Documentation Solutions</strong><span class="navi-description">about our documentation</span></span>
    <% end %>
    <ul class="sub-menu">
      <li><%= link_to administration_path do %><span>Program Administration</span><% end %></li>
      <li><%= link_to oversight_path do %><span>Medical Oversight</span><% end %></li>
      <li><%= link_to monitor_path do %><span>Compliance Monitor</span><% end %></li>
      <li><%= link_to services_path do %><span>Documentation Solutions</span><% end %></li>
    </ul>
  </li><!-- END SERVICES MENU -->
</ul>

app/views/layouts/_top_toolbar_left.erb
<div class="sub-nav">
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li>Phone:  612-729-1888</li>
    <li><%= link_to 'Contact Us', new_contact_path %></li>
  </ul>
</div>

app/views/layouts/_top_toolbar_right.erb
<div class="sub-nav2">
  <ul>
    <li><%= link_to 'Customer Login', login_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head><!-- HEAD TAG -->
  <%= render 'layouts/head_tag' %>
</head><!-- END HEAD TAG -->
<body>
<div id="wrapper"><!-- MAIN WRAPPER -->
  <div id="header"><!-- HEADER -->
    <div class="top-block"><!-- TOP BLOCK -->
      <div class="top-holder"><!-- TOP HOLDER -->
        <%= render 'layouts/top_toolbar_left' %>
        <%= render 'layouts/top_toolbar_right' %>
      </div><!-- END TOP HOLDER -->
    </div><!-- END TOP Block -->
    <div class="header-holder"><!-- HEADER HOLDER -->
      <div class="rays"><!-- RAYS -->
        <div class="header-area"><!-- HEADER AREA -->
          <%= render 'layouts/header_area' %>
        </div><!-- END HEADER AREA -->
      </div><!-- END RAYS -->
    </div><!-- END HEADER HOLDER -->
  </div><!-- END HEADER -->
  <div id="main">
    <%= yield %>
    <div id="footer"><!-- TOP FOOTER -->
      <div class= "footer-area"><!-- FOOTER AREA -->
        <div class="footer-wrapper"><!-- FOOTER WRAPPER -->
          <div class="footer-holder"><!-- FOOTER HOLDER -->
            <%= render 'layouts/footer' %>
          </div><!-- END FOOTER HOLDER -->
        </div><!-- END FOOTER WRAPPER -->
      </div><!-- END FOOTER AREA -->
    </div><!-- END FOOTER -->
    <div id=footer_bottom><!-- FOOTER BOTTOM -->
      <%= render 'layouts/footer_bottom' %>
    </div><!-- END FOOTER BOTTOM -->
  </div><!-- END MAIN -->
</div><!-- END MAIN WRAPPER -->
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head><!-- HEAD TAG -->
  <%= render 'layouts/head_tag' %>
</head><!-- END HEAD TAG -->
<body>
<div id="wrapper" class="big-banner"><!-- MAIN WRAPPER -->
  <div id="header"><!-- HEADER -->
    <div class="top-block"><!-- TOP BLOCK -->
      <div class="top-holder"><!-- TOP HOLDER -->
        <%= render 'layouts/top_toolbar_left' %>
        <%= render 'layouts/top_toolbar_right' %>
      </div><!-- END TOP HOLDER -->
    </div><!-- END TOP Block -->
    <div class="header-holder"><!-- HEADER HOLDER -->
      <div class="rays"><!-- RAYS -->
        <div class="header-area"><!-- HEADER AREA -->
          <%= render 'layouts/header_area' %>
          <%= render 'home/homepage_slider' %>
        </div><!-- END HEADER AREA -->
      </div><!-- END RAYS -->
    </div><!-- END HEADER HOLDER -->
  </div><!-- END HEADER -->
  <div id="main">
    <%= yield %>
    <div id="footer"><!-- FOOTER -->
      <div class= "footer-area"><!-- FOOTER AREA -->
        <div class="footer-wrapper"><!-- FOOTER WRAPPER -->
          <div class="footer-holder"><!-- FOOTER HOLDER -->
            <%= render 'layouts/footer' %>
          </div><!-- END FOOTER HOLDER -->
        </div><!-- END FOOTER WRAPPER -->
      </div><!-- END FOOTER AREA -->
    </div><!-- END FOOTER -->
    <div id=footer_bottom><!-- FOOTER BOTTOM -->
      <%= render 'layouts/footer_bottom' %>
    </div><!-- END FOOTER BOTTOM -->
  </div><!-- END MAIN -->
</div><!-- END MAIN WRAPPER -->
<%= debug(params) if Rails.env.development? %>
</body>
</html>